pipeline {
  agent any
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Build Java Application') {
      steps {
        // Assuming Maven for building the Java application
         sh 'mvn clean install'
       }
    }
    //stage('Build Docker Image') {
    //  steps {
    //    script {
          // Build the Docker image using the Dockerfile
    //      docker.build("ubuntu/HelloWorld.java:latest")
    //    }
   //  }
  // }
  // stage('Run Docker Container') {
   //  steps {
   //    script {
         // Run the Docker container
   //      docker.image("your-dockerhub-username/HelloWorld.java:latest").run()
  //     }
  //   }
//   }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
